### ISSUE TITLE
Option to specify SSL for postgres connection

### ISSUE THREAD

**Issue by varun-dhawan** [dalibo/sqlserver2pgsql#70]
Hi Team
Can you please allow / enable the option to allow for SSL for incoming connections from kettle jobs (*.KTR) when it doing the data transfer from SQL Server to PostgreSQL?

if this is not a doable options in main codebase, can you please share a workaround?

Thanks, Varun

**Comment by marco44** [comment]
Hi,

Which connection do you want to encrypt, and what is the problem precisely ?

**Comment by varun-dhawan** [comment]
Hi Marco
I would want the connections to use SSL, when they try to connect to postgreSQL Server from kettle jobs to transfer the data. The JDBC connection string should use SSL connections

**Comment by marco44** [comment]
Hi,

The JDBC driver uses SSL by default when the server provides it. If you want to be sure, you can forbid connection without SSL (just use hostssl instead of host in pg_hba.conf for your rules).

**Comment by varun-dhawan** [comment]
Hi Marco

I cannot make any changes to pg_hba.conf. Instead I need to force SSL connection
For example: If my db name is “foo”, I need to pass “foo?ssl=XXXXXXXXXXXXXXXXXXXXNonValidatingFactory” to allow kettle job connect to my DB

So ‘sqlserver2pgsql.pl’ file can have an option to create kettle jobs (*.ktr) that can have database name specified in above format.

**Comment by marco44** [comment]
b42f3959fba1eeb58a64e12acdb366a8823bc2cb should solve this issue. Please test

**Comment by varun-dhawan** [comment]
Thanks Marco!
I'll be testing the new code and will update you

P.S. Apologies of late reply, I've been travelling, away from mails

**Comment by varun-dhawan** [comment]
Hi Marco

The below kitchen command is still failing due to below:

**sqlserver2pgsql.pl -b before.sql -a after.sql -u unsure.sql 
-k "E:\sqlserver2pgsql-master\data_dump" 
-sd credit -sh <sql_source_server> -si <sql_source_instance> -sp 1433 -su testuser -sw ********* 
-pd credit -ph <postgres_destination> -pp 5432 -pu testuser -pw ******** **-pforce_ssl 1** 
-f SQLtabledump.sql**

In ‘migration.kjb’, there are two additional data flow steps:
a.	SQL Script Start
b.	SQL Script End
Both of them cannot connect to PostgreSQL destination, since do not have SSL options specified automatically, as oppose to other *.ktr jobs that now have ‘ssl’ and ‘sslfactory’ specified in options (refer screen below)

Can this be corrected or am I missing something, please advise

![image](https://user-images.githubusercontent.com/19426853/29261755-d95e6b18-80ee-11e7-9176-a7beba1327ca.png)
![image](https://user-images.githubusercontent.com/19426853/29261762-dec8d8b8-80ee-11e7-9d08-5af8c66ed685.png)

Thanks, Varun

**Comment by marco44** [comment]
Woops you're right. I'll make a patch

**Comment by marco44** [comment]
Should be solved by commit d2d8ab0ec74a0c74399c0a7151f904148d8e93b4

**Comment by varun-dhawan** [comment]
Thanks Marco!

I'll be testing on the new commit code and will update you if this goes well

**Comment by varun-dhawan** [comment]
Hi Marco
I am still getting the same error i.e. the [SQL Script Start] and [SQL Script Start] data flow does not have SSL options specified.  The only option is see is 'reWriteBatchedInserts = true'

**Comment by marco44** [comment]
Yeah, I forgot one part of the patch. Should be ok this time

**Comment by varun-dhawan** [comment]
Thanks Marco
The code is working fine now!

**Comment by marco44** [comment]
Great !
